### PR TITLE
refactor(toggle): remove imperative calls to updateSelectionState

### PR DESCRIPTION
**Pull request by elite-benni**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [x] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

There are some imperative calls to update the state.

Closes #

## What is the new behavior?

The state is derived in a more reactive way.
The state of the toggle is more coupled to the group (when inside a group).

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by elite-benni** [comment]
@ashley-hunter where did you see the problem with change-detection? 
I now removed it, because everything seemed to work just fine

**Comment by ashley-hunter** [comment]
> @ashley-hunter where did you see the problem with change-detection? I now removed it, because everything seemed to work just fine

I believe the change detection stuff predated my changes, I actually intended to remove it, I just forgot. Signal reads in a template will mark the view as dirty, so you are correct, it shouldn't be required anymore. 

Nice cleanup! This component is now a fraction of the original complexity!

**Comment by elite-benni** [comment]
We need to call detechChanges for the computed to be triggered. 
Tests are passing now.

**Comment by goetzrobin** [comment]
Might be worth a blog post 👀👀

**Comment by goetzrobin** [comment]
@elite-benni happy to merge once you mark it as ready to review

**Pull request merged**
