### PR TITLE
refactor(context-menu): migrate to signals (#418)

### LINKED ISSUE #418: refactor(menu): migration to signals
### Which scope/s are relevant/related to the feature request?

menubar

### Information

Migrate away from all Input/Output and View Decorators

### Describe any alternatives/workarounds you're currently using

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by MerlinMoos**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [x] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [x] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [x] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

Closes #418 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by goetzrobin** [comment]
@MerlinMoos an e2e test is failing. Can you take a look?

**Comment by MerlinMoos** [comment]
@goetzrobin of course, I will fix it

**Comment by benpsnyder** [comment]
@MerlinMoos could you please address `apps/ui-storybook-e2e/src/integration/menu/dropdown-menu.cy.ts` line 56 "/* TODO: ..." as part of this PR?

**Review by elite-benni — CHANGES_REQUESTED** [review]
Thanks for the PR! 
Left comments about the #private syntax

**Pull request merged**
