### PR TITLE
docs(tooltip): add simple string tooltip example

### LINKED ISSUE #371: Simplified tooltip experience
### Which scope/s are relevant/related to the feature request?

tooltip

### Information

I think, it would be very nice to add a version of tooltip that can be used as a simple string input directive, without declaration of nested components and additional elements for every tooltip. 
The solution could work as the Angular Material tooltip: https://material.angular.io/components/tooltip/overview.
For most use cases where advanced tooltip customizations are not required this solution would be good enough and include much less code/boilerplate.
Directive input could be used to pass a template, innerHtml content or simple string

### Describe any alternatives/workarounds you're currently using

_No response_

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [X] No

### PR DESCRIPTION
**Pull request by OlegSuncrown**
#371

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [x] tooltip
- [ ] typography

## What is the current behavior?
Closes #371

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by OlegSuncrown** [comment]
Maybe it is better to name something like "Default" to "Template tooltip" and "Simple" to "String tooltip"

**Comment by goetzrobin** [comment]
Thanks for your work on this @OlegSuncrown! 

I think I would go with Simple Tooltip and Custom Tooltip. What do you think?

Also, this is not a blocker for docs, but I am wondering if we should add another selector to the TooltipTrigger so one could do something like [hlmTooltipShowing]="'Simple text goes here'".

What do you think?

**Comment by OlegSuncrown** [comment]
@goetzrobin  Thanks for what you are doing. I can change on Simple Tooltip and Custom Tooltip.

**Comment by OlegSuncrown** [comment]
> Also, this is not a blocker for docs, but I am wondering if we should add another selector to the TooltipTrigger so one could do something like [hlmTooltipShowing]="'Simple text goes here'".
> 
> What do you think?

I think we could rename [hlmTooltipTrigger] on something like [tooltipContent], and do it similar to PrimeNg ?
image

**Comment by elite-benni** [comment]
> Thanks for your work on this @OlegSuncrown!
> 
> I think I would go with Simple Tooltip and Custom Tooltip. What do you think?
> 
> Also, this is not a blocker for docs, but I am wondering if we should add another selector to the TooltipTrigger so one could do something like [hlmTooltipShowing]="'Simple text goes here'".
> 
> What do you think?

This means that an additional input is needed, or is there a trick to use the one input for both selectors? 
To Me the PR looks good.

**Review by goetzrobin — APPROVED** [review]

**Comment by OlegSuncrown** [comment]
> > This means that an additional input is needed, or is there a trick to use the one input for both selectors? To Me the PR looks good.
> 
> No I agree that we would need two inputs

@goetzrobin @elite-benni sorry for my late answer. It looks like new input is not required, from what I see, this is already working:

pass template as import

```html
<button [hlmTooltipTrigger]="template" hlmBtn variant="outline">Html</button>

<ng-template #template>
	<div class="flex items-center">
		My html tooltip
		<hlm-icon class="ml-2" size="sm" name="lucidePlus" />
	</div>
</ng-template>
```

pass string as import

```html
<button [hlmTooltipTrigger]="'My string tooltip'"hlmBtn variant="outline">
	String
</button>
```

And if you like this version, I think this <hlm-tooltip></hlm-tooltip> can be removed at all.

**Pull request merged**
